### ISSUE TITLE
Multiple servers pulling same JID from queue 

### ISSUE THREAD

**Issue by kylebush** [jrallison/go-workers#38]
After I have enqueued multiple jobs, I am running multiple servers to pull jobs from the queue and process them.  Occasionally, the same JID is pulled by two servers which I had assumed could not happen.  I am following the simple example from the README:

```
func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	workers.Process("LogParser", parseLog, 1)
	workers.Run()

}
```

The workers are configured in the init() specifying the server, database, namespace, pool and process.

Is there additional configuration/code to ensure this does not happen?

**Comment by jrallison** [comment]
Hey Kyle,

Sorry for the late response!

I'm not aware of any issues around this. Can you provide more information? Your configuration of go-workers, the jobs you're running, logs, a failing test-case, etc, etc?

I'm happy to investigate. Closing for now, but please re-open if you'd like to continue.

Cheers,
John

**Comment by jrallison** [comment]
Actually... looking at you're code, you're setting it to run over all CPUs:

`runtime.GOMAXPROCS(runtime.NumCPU())`

Which could potentially cause issues. All our testing runs workers with the default number of GOMAXPROCS (or 1).  This is how we run it in production as well.

I'd suggest doing the same until we specifically say the library works well in a multi-cpu environment.
