### ISSUE TITLE
Could you add an option for the POLL_INTERVAL in enqueue.go

### ISSUE THREAD

**Issue by mail2fish** [jrallison/go-workers#39]
15 secs is a little long for our situation. If that is an option, that is great.

Thanks for your project. That's very nice.

**Comment by jrallison** [comment]
Hey there, we just merged in a change to make the poll interval configurable. Let me know if there's anything else you're running into.

**Comment by mail2fish** [comment]
Thank you. I have pulled that commit. It's nice. 

Can we use millisecond instead of  second in poll interval?

Actually, in my case, we poll the job by 500 milliseconds.

Thank you again.

**Comment by mail2fish** [comment]
I did that change in my fork. But I don't how to submit to you.
