### ISSUE TITLE
Example of not acknowledging a message?

### ISSUE THREAD

**Issue by nathany** [jrallison/go-workers#48]
There appears to be an Acknowledge() function on the Fetcher and some acknowledgement options on middleware, but not on "myJob".

If my job can't be processed yet and I would like to leave it on the inProgressQueue, how do I do that? 

It's also not clear to me when those inProgress jobs are retried? Is that dependent on retry options sent from the (Ruby client)? Does it use [the same backoff algorithm](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry) as the Sidekiq server?

**Comment by jrallison** [comment]
Hey @nathany,

If the job panics, the default retry middleware (https://github.com/jrallison/go-workers/blob/master/middleware_retry.go) will pick it up and place it the retry queue which behaves just like Sidekiq's does (places it in a redis sorted set, and exponentially backs off if it continues to fail).

Hope that helps!

Cheers,
John

**Comment by nathany** [comment]
Oh, so I should force a panic in the job if it's not ready to acknowledge it?

Doesn't seem the most Go-like, not a truly exceptional condition.

**Comment by rowland** [comment]
I'm glad to have found this thread. I was looking all over for a way to avoid calling panic(). Exceptions as flow control are not idiomatic Go, so I was sure I must be mistaken.
