### ISSUE TITLE
EnqueueIn method error

### ISSUE THREAD

**Issue by huoshiqiu** [jrallison/go-workers#57]
I use golang to set up a sidekiq client and a ruby sidekiq worker,

I felt very good when use **Enqueue** method just like this:
```ruby
 workers.Enqueue("example", "SomeWorker", "some_string")
```

But it will get some error when i use **EnqueueIn** method for some delayed job,
like this:
```ruby
 workers.EnqueueIn("example", "SomeWorker", 10, "some_string")
```

```ruby
error: 
  Message args must be an Array
  /.rvm/gems/ruby-2.2.2/gems/sidekiq-3.2.6/lib/sidekiq/client.rb:212:in `normalize_item'
```
would i doing something wrong?

sorry to my pool english!

**Comment by Soulou** [comment]
Sidekiq is expexcting an array of arguments, please try

```
 workers.EnqueueIn("example", "SomeWorker", 10, []string{"some_string"})
```

**Comment by huoshiqiu** [comment]
@Soulou have tried array of arguments already, get the same error

**Comment by Soulou** [comment]
@huoshiqiu here are some working examples: https://github.com/Soulou/go-workers-sidekiq-example

```
	workers.EnqueueIn(defaultQueue, "HelloWorker", 1.0, []string{"Soulou"})
```

This is working as expected.

**Comment by huoshiqiu** [comment]
@Soulou so Thx, it seem to be ok
