### ISSUE TITLE
What's the meaning of "Class" property in EnqueueData？

### ISSUE THREAD

**Issue by iCoolchar** [jrallison/go-workers#62]
I have been using go worker for a while and it seems I never need to use class property in EnqueueData. So what's the meaning of it. Can I just ignore it? Thanks!

**Comment by jrallison** [comment]
It's for compatibility with Sidekiq (allows you to enqueue jobs in golang to be processed by ruby workers or visa-versa). Sidekiq encodes the Class of the job which should process the message in the message itself: https://github.com/mperham/sidekiq/wiki/The-Basics

If you're simply using go-workers in golang, you can ignore it as you must specify the job which processes each queue in your code.

**Comment by AAlvarez90** [comment]
Thanks for creating this issue. I was wondering the same thing.

**Comment by AAlvarez90** [comment]
@jrallison I am curious what's your take on this.
I am using your package in a small app that would need to have a separate "worker" version of it in a different server. The classic rails story. A web server, redis, the worker. 
But in this case everything is in Golang. Could we have modifications so we can enqueue without having to add that Class argument? I am not well aware of the ins and out of this package so I apologize for the ignorance in advance.
